package br.com.mvvm.teste.webservice.domain


data class Payload(
    val cod_pessoa: Int,
    val cod_usuario: Int,
    val cod_classif_pessoa: Int,
    val nom_pessoa: String,
    val cod_cpf: String,
    val des_endereco: String,
    val des_nro_endereco: Int,
    val des_complemento: String,
    val des_nro_celular: String,
    val dat_aniversario: String,
    val des_sexo: Int,
    val bol_ativo: Int,
    val dat_cadastro: String,
    val dat_alteracao: String,
    val qtd_filhos: Int,
    val bol_utiliza_crm: Int,
    val des_cep: String,
    val des_cidade: String,
    val des_estado: String,
    val des_telefone_fixo: Any,
    val des_bairro: String,
    val cod_equipe: Int,
    val dia_aniversario: Int,
    val mes_aniversario: Int,
    val bol_sms_cadastro: Int,
    val cod_contato: Int,
    val des_email: String,
    val cod_loja: Int,
    val bol_email_cadastrado: Any,
    val bol_email_valido: Int,
    val img_pessoa: Any,
    val flg_criado_conductor: Boolean,
    val id_cartao: Int,
    val id_portador: Int
)